In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression 

In [5]:
data = pd.read_csv(r"F:\jupyter\dsbootcamp\data\1.02. Multiple linear regression.csv")
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
5   1670  2.91           1
6   1764  3.00           2
7   1764  3.00           1
8   1792  3.01           2
9   1850  3.01           3
10  1735  3.02           3
11  1775  3.07           2
12  1735  3.08           1
13  1712  3.08           3
14  1773  3.12           2
15  1872  3.17           2
16  1755  3.17           3
17  1674  3.17           2
18  1842  3.17           3
19  1786  3.19           3
20  1761  3.19           3
21  1722  3.19           3
22  1663  3.20           3
23  1687  3.21           1
24  1974  3.24           1
25  1826  3.28           1
26  1787  3.28           1
27  1821  3.28           3
28  2020  3.28           1
29  1794  3.28           2
..   ...   ...         ...
54  1879  3.44           1
55  1887  3.47           1
56  1730  3.47           2
57  1953  3.47           1
58  1781  3.47           2
59  1891  3.48           2
60  1964  3.49           1
61  1808  3.49           3
62  1893  3.50           3
63  2041  3.51           3
64  1893  3.51           1
65  1832  3.52           2
66  1850  3.52           3
67  1934  3.54           2
68  1861  3.58           2
69  1931  3.58           3
70  1933  3.59           3
71  1778  3.59           1
72  1975  3.60           1
73  1934  3.60           3
74  2021  3.61           3
75  2015  3.62           3
76  1997  3.64           1
77  2020  3.65           2
78  1843  3.71           3
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [6]:
x1 = data[['SAT','Rand 1,2,3']]
y=data['GPA']


In [7]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [8]:
reg=LinearRegression()

In [9]:
reg.fit(x1,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [10]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [11]:
reg.intercept_

0.29603261264909486

## R squared

In [13]:
reg.score(x1,y)

0.4066811952814285

##  adj R squared

## R^2_(adj.)=1-(1-R^2)*\frac (n-1)(n-p-1)   - running this code with $ sympble front and back will get below forumula


$R^2_(adj.)=1 - (1-R^2)*\frac(n-1)(n-p-1)$

In [15]:
x1.shape

(84, 2)

In [17]:
r2 = reg.score(x1,y)
n = x1.shape[0]    # 84 
p = x1.shape[1]   #2


In [18]:
R2 = 1-(1-r2)*(n-1)/(n-p-1)

In [19]:
R2

0.39203134825134023

## feature selection (p-value)(f-statistics)

In [20]:
from sklearn.feature_selection import f_regression

In [21]:
f_regression(x1,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

#### above code first array indicates f-statistics and 2nd array indicates p-values

In [23]:
p_values= f_regression(x1,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [25]:
p_values.round(3)

array([0.   , 0.676])

#### first value came for sat and second value is for random 123

# creating summary tabel


In [26]:
reg_summary = pd.DataFrame(data=x1.columns.values,columns=['features'])
reg_summary

features
0         SAT
1  Rand 1,2,3

In [28]:
reg_summary['Coeffience']= reg.coef_
reg_summary['p-value']= p_values.round(3)

In [29]:
reg_summary

features  Coeffience  p-value
0         SAT    0.001654    0.000
1  Rand 1,2,3   -0.008270    0.676