In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression 

In [2]:
data = pd.read_csv(r"F:\jupyter\dsbootcamp\data\1.02. Multiple linear regression.csv")
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
5   1670  2.91           1
6   1764  3.00           2
7   1764  3.00           1
8   1792  3.01           2
9   1850  3.01           3
10  1735  3.02           3
11  1775  3.07           2
12  1735  3.08           1
13  1712  3.08           3
14  1773  3.12           2
15  1872  3.17           2
16  1755  3.17           3
17  1674  3.17           2
18  1842  3.17           3
19  1786  3.19           3
20  1761  3.19           3
21  1722  3.19           3
22  1663  3.20           3
23  1687  3.21           1
24  1974  3.24           1
25  1826  3.28           1
26  1787  3.28           1
27  1821  3.28           3
28  2020  3.28           1
29  1794  3.28           2
..   ...   ...         ...
54  1879  3.44           1
55  1887  3.47           1
56  1730  3.47           2
57  1953  3.47           1
58  1781  3.47           2
59  1891  3.48           2
60  1964  3.49           1
61  1808  3.49           3
62  1893  3.50           3
63  2041  3.51           3
64  1893  3.51           1
65  1832  3.52           2
66  1850  3.52           3
67  1934  3.54           2
68  1861  3.58           2
69  1931  3.58           3
70  1933  3.59           3
71  1778  3.59           1
72  1975  3.60           1
73  1934  3.60           3
74  2021  3.61           3
75  2015  3.62           3
76  1997  3.64           1
77  2020  3.65           2
78  1843  3.71           3
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [3]:
x = data[['SAT','Rand 1,2,3']]
y=data['GPA']


## standardization

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scaler= StandardScaler() # standarscaler used to subtract the mean and divided by  the standard deviation

In [6]:
scaler.fit(x) # just creating standardization mechanism

C:\Users\Sivaram\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
x_scaled = scaler.transform(x)  # transofrms the unscaled inputs into scaler object. Refer sklearn documentation

C:\Users\Sivaram\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [10]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [11]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [12]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [13]:
reg.intercept_

3.330238095238095

# creating a summary table

In [14]:
reg_summary = pd.DataFrame([['Intercept or bias'],['SAT'],['Rand 1,2,3']])

In [15]:
reg_summary['weights or coefficient']= reg.intercept_,reg.coef_[0],reg.coef_[1]

In [16]:
reg_summary

0  weights or coefficient
0  Intercept or bias                3.330238
1                SAT                0.171814
2         Rand 1,2,3               -0.007030

## making predictions


In [19]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]],columns= ['sat','Rand 1,2,3'])
new_data

sat  Rand 1,2,3
0  1700           2
1  1800           1

### if we predict this we get different value since our model is based on standardized coefficients

In [20]:
reg.predict(new_data)

array([295.39979563, 312.58821497])

### convert new df to standardized df

In [21]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

C:\Users\Sivaram\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [23]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

# what happen if we removed rand 1,2,3? 
### according to sklearn both value should be same

In [24]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [25]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

### if u compare them the values are almost same when we round upto 2 points excatly same 