In [52]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd

In [6]:
a=np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
train_test_split(a) # will divided the data into random 2 arrays

[array([ 24,  35,  42,  89,  70,  12,  58,  77,  68,  64,  25,   9,  66,
          3,  54,  30,  86,  78,  97,  37,  61,  90,  82,  50,  93,  49,
         81,  55,  52,  92,  72,  47,  26,  75,  69,  46,   2,  98,  56,
         40,  71,  36,  83,  99,  21,  91,   1,  22,  16,  39,  94,  38,
         48,  84,  15,  88,  57,   6,  63,  23,  79,  96,  59, 100,  95,
         33,  28,   7,  19,  43,  14,  20,  65,  45,  76]),
 array([ 5, 18, 73, 87, 31, 85, 53, 10, 74, 32, 13, 67, 80, 34,  8, 51, 27,
        44, 11, 62, 17,  4, 41, 29, 60])]

In [8]:
a_train,a_test = train_test_split(a)


In [9]:
a_train.shape

(75,)

In [10]:
a_test.shape

(25,)

# default split is 75:25 but generally ml uses 80:20


In [17]:
a_train,a_test = train_test_split(a,test_size=0.2)   # test_size incdicates the divide values for eg 0.4 is 40 in this example

In [18]:
a_train.shape

(80,)

In [19]:
a_test.shape

(20,)

# no shuffle
## in some cases we do not need shuffle data so by default is shuffle = True


In [28]:
a_train,a_test = train_test_split(a,test_size=0.2,shuffle= False)   # to trunoff shuffle

In [29]:
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [30]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

## in shuffle there is a issue everytime u shuffle new data will come to stop that we can use 

In [37]:
a_train,a_test = train_test_split(a,test_size=0.2,random_state=42)   # 42 is community using but we can choose any number for eg 35

In [38]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [39]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

# to split more df at single time

In [40]:
#lets create one new array

In [41]:
b = np.arange(400,501)

In [42]:
b

array([400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
       413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
       426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
       439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
       452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
       465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
       478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490,
       491, 492, 493, 494, 495, 496, 497, 498, 499, 500])

In [50]:
a_train, a_test, b_train, b_test = train_test_split(a,b,test_size=0.25,random_state=32)

ValueError: Found input variables with inconsistent numbers of samples: [100, 101]